services:
  common:
    rabbitmq:
      host: localhost
      port: 5672
      username: test
      password: test
      virtual_host: nesta_server
      queue: "server"
    mysql:
      host: 0.0.0.0
      port: 3306
      username: test
      password: test
      db: nesta
    celery:
      backend: rpc://
      broker: amqp://test:test@localhost/nesta_worker
  server:
    host: localhost
    port: 9000
    interval: 2
    log_path: "{ROOT_PATH}/log"
    log_level: "DEBUG"
    auto_start: true
