services:
  common:
    rabbitmq:
      host: localhost
      port: 5672
      username: test
      password: test
      virtual_host: regista_server
      queue: "server"
    mysql:
      host: 0.0.0.0
      port: 3306
      username: test
      password: test
      db: regista
    celery:
      backend: rpc://
      broker: amqp://test:test@localhost/regista_worker
  server:
    host: localhost
    port: 9000
    auto_start: true
